name: Build

on:
  release:
    types: [published]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install build dependencies
        run: python -m pip install -r requirements.txt

      - name: Install Scilpy dependencies
        run: bash prepare_scilpy.sh

      - uses: actions/checkout@v4
        with:
          repository: scilus/scilpy
          path: scilpy

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: 3.10
          CIBW_BUILD_FRONTEND: build

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl